name: Rodrigo Dumont

pygments: true
safe: true
timezone: America/Sao_Paulo
permalink: pretty
exclude:
  - "*.less"

title: Rodrigo Dumont
author:
  name: Rodrigo Dumont
  email: rlsdumont@gmail.com
  github: rdumont
  twitter: rlsdumont

production_url: http://rodrigodumont.com

navigation:
  - text: Blog
    url: /
    group: post
  - text: Work
    url: /work/
  - text: About
    url: /about/
